services:
  postgres:
    image: postgres:latest
    hostname: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./raw_data:/raw_data
    restart: unless-stopped

volumes:
  postgres_data:

